### ISSUE TITLE
Use website favicon for custom tabs

### ISSUE THREAD

**Issue by timpulver** [jonasjohansson/browser#9]
When adding a custom tab with `⌘ + 9` it would be nice if it showed the website’s favicon instead of the unicorn in the tab bar.

**Comment by alexanderwallin** [comment]
It'd be nice to scan `<head>` for any larger icons defined by `<link>` tags as described here: https://stackoverflow.com/a/5635018/519531

**Comment by jonasjohansson** [comment]
Added! Could probably be a bit more intelligent approach other than a node package atm… Also tried the link route which gave similar results. Seems to work forn ow.
